# Generated by Django 5.2.17 on 2026-09-13 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('telemetry', '0003_trafficwindow_capture_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('manifest', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_digest', models.CharField(editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_digest', models.CharField(editable=False, max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('scored_at', models.DateTimeField()),
                ('anomaly_score', models.FloatField()),
                ('label', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ANOMALOUS', 'ANOMALOUS')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitoringsession')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.trafficwindow')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='detection.modelversion')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'observed_at'], name='score_session_observed_idx')],
                'constraints': [models.UniqueConstraint(fields=('window', 'model_version'), name='score_window_model_unique'), models.CheckConstraint(condition=models.Q(('label__in', ['NORMAL', 'ANOMALOUS'])), name='score_label_valid'), models.CheckConstraint(condition=models.Q(('anomaly_score__gte', 0), ('anomaly_score__lte', 1)), name='score_bounds')],
            },
        ),
    ]
