# Generated by Django 5.2.17 on 2026-09-12 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField()),
                ('run_id', models.UUIDField(db_index=True)),
                ('interface_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('LIVE', 'Live'), ('SIMULATION', 'Simulation'), ('REPLAY', 'Replay')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('observation_profile', models.CharField(max_length=80)),
                ('schema_version', models.CharField(default='backend-v1', max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_digest', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ['LIVE', 'SIMULATION', 'REPLAY'])), name='session_mode_valid')],
            },
        ),
        migrations.CreateModel(
            name='CaptureStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_digest', models.CharField(editable=False, max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('RUNNING', 'Running'), ('INTERFACE_LOST', 'Interface Lost'), ('RECOVERING', 'Recovering'), ('STOPPED', 'Stopped')], max_length=20)),
                ('valid', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('loss_started_at', models.DateTimeField(blank=True, null=True)),
                ('gap_ended_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_gap_seconds', models.FloatField(default=0)),
                ('recovery_attempts', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitoringsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'observed_at'), name='status_session_observed_unique'), models.CheckConstraint(condition=models.Q(('state__in', ['RUNNING', 'INTERFACE_LOST', 'RECOVERING', 'STOPPED'])), name='status_state_valid'), models.CheckConstraint(condition=models.Q(('monitoring_gap_seconds__gte', 0)), name='status_gap_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'RUNNING'), ('valid', True)), models.Q(models.Q(('state', 'RUNNING'), _negated=True), ('valid', False)), _connector='OR'), name='status_validity_consistent')],
            },
        ),
    ]
