# Generated by Django 5.2.17 on 2026-09-12 17:05

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_digest', models.CharField(editable=False, max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('elapsed_seconds', models.FloatField()),
                ('measurement_source', models.CharField(default='OS_COUNTERS', max_length=20)),
                ('valid', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('bytes_sent', models.PositiveBigIntegerField()),
                ('bytes_received', models.PositiveBigIntegerField()),
                ('packets_sent', models.PositiveBigIntegerField()),
                ('packets_received', models.PositiveBigIntegerField()),
                ('delta_bytes_sent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('delta_bytes_received', models.PositiveBigIntegerField(blank=True, null=True)),
                ('delta_packets_sent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('delta_packets_received', models.PositiveBigIntegerField(blank=True, null=True)),
                ('upload_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('download_bytes_per_second', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitoringsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'observed_at'), name='sample_session_observed_unique'), models.CheckConstraint(condition=models.Q(('elapsed_seconds__gt', 0)), name='sample_elapsed_positive'), models.CheckConstraint(condition=models.Q(models.Q(('download_bytes_per_second__gte', 0), ('download_bytes_per_second__isnull', False), ('reason__isnull', True), ('upload_bytes_per_second__gte', 0), ('upload_bytes_per_second__isnull', False), ('valid', True)), models.Q(('download_bytes_per_second__isnull', True), ('reason__isnull', False), ('upload_bytes_per_second__isnull', True), ('valid', False)), _connector='OR'), name='sample_validity_consistent')],
            },
        ),
        migrations.CreateModel(
            name='TrafficWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_digest', models.CharField(editable=False, max_length=64)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('finalized_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField()),
                ('measurement_source', models.CharField(default='PACKET_METADATA', max_length=20)),
                ('schema_version', models.CharField(default='backend-window-v1', max_length=40)),
                ('partial', models.BooleanField()),
                ('valid', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('packets', models.PositiveBigIntegerField()),
                ('ip_bytes', models.PositiveBigIntegerField()),
                ('outbound_packets', models.PositiveBigIntegerField()),
                ('inbound_packets', models.PositiveBigIntegerField()),
                ('unknown_packets', models.PositiveBigIntegerField(default=0)),
                ('outbound_bytes', models.PositiveBigIntegerField()),
                ('inbound_bytes', models.PositiveBigIntegerField()),
                ('unknown_bytes', models.PositiveBigIntegerField(default=0)),
                ('tcp_packets', models.PositiveBigIntegerField()),
                ('udp_packets', models.PositiveBigIntegerField()),
                ('other_packets', models.PositiveBigIntegerField(default=0)),
                ('flow_count', models.PositiveIntegerField()),
                ('dropped', models.PositiveIntegerField(default=0)),
                ('kernel_loss', models.CharField(default='unknown', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitoringsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'start'), name='window_session_start_unique'), models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='window_time_order'), models.CheckConstraint(condition=models.Q(('packets', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('outbound_packets'), '+', models.F('inbound_packets')), '+', models.F('unknown_packets')))), name='window_packet_conservation'), models.CheckConstraint(condition=models.Q(('ip_bytes', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('outbound_bytes'), '+', models.F('inbound_bytes')), '+', models.F('unknown_bytes')))), name='window_byte_conservation'), models.CheckConstraint(condition=models.Q(('packets', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('tcp_packets'), '+', models.F('udp_packets')), '+', models.F('other_packets')))), name='window_protocol_conservation'), models.CheckConstraint(condition=models.Q(models.Q(('dropped', 0), ('partial', False), ('reason__isnull', True), ('valid', True)), models.Q(('partial', True), ('reason__isnull', False), ('valid', False)), _connector='OR'), name='window_validity_consistent')],
            },
        ),
    ]
