# Generated by Django 5.2.17 on 2026-09-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trafficwindow',
            index=models.Index(fields=['session', 'end'], name='window_session_end_idx'),
        ),
    ]
