# Generated by Django 5.2.17 on 2026-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_trafficwindow_window_session_end_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficwindow',
            name='capture_context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficwindow',
            name='feature_schema_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='trafficwindow',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
