"use strict";
const $ = (id) => document.getElementById(id);
let accessKey = "";
let state = null;
let busy = false;
const titles = {overview:"Your computer, at a glance.",apps:"Every app. A clearer picture.",security:"Protection, without the guesswork.",history:"Follow the observed traffic.",reports:"Useful evidence, ready to share.",guide:"Make NetSentinel work for you."};
const bytes = (n) => n == null ? "Unavailable" : n < 1024 ? `${n} B` : n < 1048576 ? `${(n/1024).toFixed(1)} KiB` : n < 1073741824 ? `${(n/1048576).toFixed(1)} MiB` : `${(n/1073741824).toFixed(2)} GiB`;
const date = (n) => n ? new Date(typeof n === "number" ? n*1000 : n).toLocaleString() : "Unavailable";
const utc = (n) => new Date(n*1000).toISOString().replace("T"," ").replace(".000Z"," UTC");
const notice = (text) => { $("notice").textContent = text; };
function element(tag, text, className) {const el=document.createElement(tag); if(text!=null)el.textContent=text;if(className)el.className=className;return el;}
async function api(path, data, pdf=false) {
  const response = await fetch(`/api/${path}`, {method:data===undefined?"GET":"POST",headers:{Authorization:`Bearer ${accessKey}`, ...(data===undefined?{}:{"Content-Type":"application/json"})}, body:data===undefined?undefined:JSON.stringify(data), cache:"no-store",redirect:"error",signal:AbortSignal.timeout(pdf?30000:28000)});
  if(!response.ok){const error=await response.json();throw Error(error.error||"Local request failed");}
  return pdf ? response.blob() : response.json();
}
async function perform(fn) {if(busy)return;busy=true;notice("");try{await fn();}catch(error){notice(error.message||"The operation could not be completed.");}finally{busy=false;}}
function row(container,label,value){const item=element("div",null,"stat-row");item.append(element("span",label),element("strong",value));container.append(item);}
function table(id,rows,empty){const body=$(id);body.replaceChildren();for(const values of rows){const tr=element("tr");for(const value of values)tr.append(element("td",value));body.append(tr);}if(!rows.length){const td=element("td",empty);td.colSpan=5;const tr=element("tr");tr.append(td);body.append(tr);}}
function events(id,items){const container=$(id);container.replaceChildren();if(!items.length)container.append(element("p","No retained observations in this category. This is not a safety verdict."));for(const event of items){const item=element("div",null,"event");item.append(element("small",`${date(event.at)} · ${event.mode} · ${event.code.replaceAll("_"," ")}`),element("p",event.message));container.append(item);}}
function renderSecurity(value){const box=$("security-details");box.replaceChildren();if(!value){box.append(element("p","Status has not been queried."));return;}$("security-observed").textContent=`Last queried ${date(value.observed_at)} · Windows interfaces · LIVE`;
  const d=value.defender;row(box,"Microsoft Defender",d.available?`${d.state} (${d.mode})`:`Unavailable: ${d.error}`);row(box,"Real-time protection",d.realtime_enabled===true?"Enabled":d.realtime_enabled===false?"Disabled":"Unavailable");row(box,"Signature updated",date(d.signature_updated_at));row(box,"Signature age",d.signature_age_seconds==null?"Unavailable":`${(d.signature_age_seconds/3600).toFixed(1)} hours`);row(box,"Last quick scan ended",date(d.quick_scan_ended_at));row(box,"Last full scan ended",date(d.full_scan_ended_at));for(const profile of value.firewall.profiles)row(box,`${profile.name} firewall`,profile.enabled===true?"Enabled":profile.enabled===false?"Disabled":"Unavailable");
}
function renderScan(value){const box=$("scan-details");box.replaceChildren();if(!value)return;row(box,"NetSentinel request",value.request?`${value.request.kind}: ${value.request.state}`:"No tracked request; Windows history may include other scans");row(box,"Observation time",date(value.observed_at));const detections=value.detections;box.append(element("p",detections.available?`${detections.items.length} available detection record(s). These are not linked to a particular scan.`:"Detection results unavailable."));for(const item of detections.items.slice(0,20))box.append(element("p",`Threat ID ${item.threat_id} · observed ${date(item.detected_at)} · remediation action ${item.action_success===true?"reported successful":item.action_success===false?"not successful":"unavailable"}`));}
function render(){if(!state)return;$("capture-state").textContent=`Observation: ${state.capture.state}${state.capture.interface?` · ${state.capture.interface}`:""}${state.capture.error?` · ${state.capture.error}`:""}`;const hasRecords=state.usage.length>0;const total=state.apps.reduce((s,a)=>s+a.today.combined,0);$("today-bytes").textContent=hasRecords?bytes(total):"No observations";$("unassigned").textContent=hasRecords?bytes(state.unassigned_today):"No observations";$("mode").textContent=state.enforcement?"Enforcement enabled":"Observation only";$("broker-state").textContent=state.broker_connected?"Privileged broker connected":"Privileged broker disconnected";$("coverage").textContent=`Last packet: ${date(state.capture.last_packet_at)}. Metadata queue drops: ${state.capture.dropped_metadata}. Parse failures: ${state.capture.parse_failures}. Kernel loss: ${state.capture.kernel_loss}. Snapshot accessible: ${state.capture.socket_snapshot_complete?"yes":"no"}.`;$("resets").textContent=`Next daily reset: ${utc(state.daily_reset)}. Next monthly reset: ${utc(state.monthly_reset)}.`;
  const names=new Map(state.apps.map(a=>[a.id,a.name]));const selected=$("quota-app").value;$("quota-app").replaceChildren();for(const a of state.apps){const option=element("option",`${a.name}${a.protected?" (protected)":""}`);option.value=a.id;$("quota-app").append(option);}if(names.has(selected))$("quota-app").value=selected;
  table("apps-table",state.apps.map(a=>[a.name,a.today.observed?`${bytes(a.today.uploaded)} ↑ / ${bytes(a.today.downloaded)} ↓`:"No attributed observations",a.month.observed?bytes(a.month.combined):"No attributed observations",`${a.protected?"Protected. ":""}${a.daily?`Day ${bytes(a.daily)}. `:""}${a.monthly?`Month ${bytes(a.monthly)}. `:""}${a.reached.length?`Reached ${a.reached.join(", ")}. `:""}${a.override>state.generated_at?`Override until ${utc(a.override)}. `:""}${state.controls[a.id]?.state?.replaceAll("_"," ")||"No applied rule recorded"}`]),"No observed executables yet. Start observation to discover available applications.");
  table("flow-table",state.flows.map(f=>[date(f.at),names.get(f.app)||"Unassigned",f.protocol,`${f.remote}:${f.port??"?"}`,`${bytes(f.up)} ↑ / ${bytes(f.down)} ↓`]),"No retained observed flows. Missing capture is not zero traffic.");events("quota-events",state.events.filter(e=>e.category==="quota"));events("security-events",state.events.filter(e=>e.category==="security"));renderSecurity(state.security);if(state.scan)renderScan(state.scan);$("last-refresh").textContent=`Refreshed ${new Date().toLocaleTimeString()}`;
}
async function refresh(){state=await api("state");render();}
async function action(name,data){const result=await api(name,data);await refresh();if(result.success===false)notice("Windows did not confirm this action. Inspect its status and run recovery if needed.");else notice(name==="control"?"Request saved. Review the rule outcome; traffic blocking is not verified.":"Request completed. Review the observed status below.");return result;}
$("login-form").addEventListener("submit",e=>{e.preventDefault();perform(async()=>{accessKey=$("access-key").value;try{await refresh();const value=await api("adapters");$("adapter").replaceChildren();for(const a of value.adapters){const option=element("option",`${a.name} (${a.up?"up":"down"})`);option.value=a.name;option.dataset.addresses=a.addresses.join(", ");$("adapter").append(option);}$("adapter").dispatchEvent(new Event("change"));$("access-key").value="";$("login").hidden=true;$("workspace").hidden=false;$("disconnect").hidden=false;}catch(error){accessKey="";throw error;}});});
$("disconnect").addEventListener("click",()=>{accessKey="";state=null;$("workspace").hidden=true;$("login").hidden=false;$("disconnect").hidden=true;notice("Dashboard locked. Observation and previously enabled quotas may continue in the companion.");});
document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-view]").forEach(b=>b.removeAttribute("aria-current"));button.setAttribute("aria-current","page");document.querySelectorAll("[data-section]").forEach(section=>section.hidden=section.dataset.section!==button.dataset.view);$("page-title").textContent=titles[button.dataset.view];$("main").focus();}));
$("adapter").addEventListener("change",()=>{$("adapter-details").textContent=`Local addresses: ${$("adapter").selectedOptions[0]?.dataset.addresses||"unavailable"}`;});
$("capture-start").onclick=()=>perform(()=>action("capture-start",{interface:$("adapter").value,consent:$("capture-consent").checked}));
$("capture-stop").onclick=()=>perform(()=>action("capture-stop",{}));
$("quota-app").onchange=()=>{const app=state?.apps.find(a=>a.id===$("quota-app").value);if(app){$("daily").value=app.daily?app.daily/1048576:"";$("monthly").value=app.monthly?app.monthly/1048576:"";$("warning").value=app.warning;$("direction").value=app.direction;$("auto-block").checked=!!app.auto;}};
$("quota-form").onsubmit=e=>{e.preventDefault();perform(()=>action("policy",{app:$("quota-app").value,changes:{daily:$("daily").value?Math.round(Number($("daily").value)*1048576):null,monthly:$("monthly").value?Math.round(Number($("monthly").value)*1048576):null,warning:Number($("warning").value),direction:$("direction").value,auto:$("auto-block").checked}}));};
$("enable-enforcement").onclick=()=>perform(()=>action("enforcement",{enabled:true,consent:$("enforcement-consent").checked}));
$("disable-enforcement").onclick=()=>perform(()=>action("enforcement",{enabled:false,consent:true}));
$("block-app").onclick=()=>perform(()=>action("control",{app:$("quota-app").value,action:"block"}));
$("unblock-app").onclick=()=>perform(()=>action("control",{app:$("quota-app").value,action:"override"}));
$("security-refresh").onclick=()=>perform(async()=>{await action("security",{});});
$("quick-scan").onclick=()=>perform(async()=>{await action("scan",{kind:"quick",consent:$("scan-consent").checked});$("scan-consent").checked=false;});
$("full-scan").onclick=()=>perform(async()=>{if(!confirm("Start a full Microsoft Defender scan? It may take a long time and will continue if you close this tab."))return;await action("scan",{kind:"full",consent:$("scan-consent").checked});$("scan-consent").checked=false;});
$("scan-refresh").onclick=()=>perform(async()=>{const value=await action("scan-status",{});renderScan(value);});
$("report-start").value=new Date(Date.now()-6*86400000).toISOString().slice(0,10);$("report-end").value=new Date().toISOString().slice(0,10);
$("report-form").onsubmit=e=>{e.preventDefault();perform(async()=>{const sections=Array.from(document.querySelectorAll('input[name="section"]:checked')).map(el=>el.value);const blob=await api("report",{sections,start:Date.parse($("report-start").value+"T00:00:00Z")/1000,end:Date.parse($("report-end").value+"T23:59:59Z")/1000,include_sensitive:$("include-sensitive").checked},true);const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="NetSentinel-local-report.pdf";link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);notice("PDF downloaded. Review it before sharing.");});};
setInterval(()=>{if(accessKey&&!busy&&!document.hidden)perform(refresh);},5000);
